import { ProjectsConfig } from '../types';
import { IMAGES } from '../assets/images';

export const projectsConfig: ProjectsConfig = {
  title: 'Work Experience',
  subtitle: 'A journey through innovation, leadership, and technical excellence across world-class organizations.',
  projects: [
    {
      id: 'walmart-staff-software-engineer',
      title: "Walmart Plus & Sam's Club membership platform",
      description: "Led modernization of Walmart's membership platforms for CA and MX markets, building scalable cloud-native experiences for high-volume customer flows.",
      imageSrc: IMAGES.projects.walmart,
      imageAlt: 'Walmart Plus and Sams Club membership platform',
      initials: 'WM',
      role: 'Staff Software Engineer',
      company: 'Walmart',
      duration: 'Sep 2023 - Present',
      location: 'Bengaluru, India',
      summary: "Led modernization of Walmart's membership platforms for CA and MX markets, building scalable cloud-native experiences for high-volume customer flows.",
      achievements: [
        'Built a tenant-agnostic unified Walmart Plus platform driving 2x subscription growth in one year.',
        "Modernized Sam's Club membership funnel with React, Next.js, TypeScript, and GraphQL improving responsiveness by ~25%.",
        'Designed caching platform reducing downstream TPS by 45% and cutting cloud spend.',
      ],
      technologies: [
        'React',
        'Next.js',
        'TypeScript',
        'GraphQL',
        'Node.js',
        'GCP',
      ],
    },
    {
      id: 'sixt-sde-3',
      title: 'Sixt mobile check-in and micro-frontend platform',
      description: 'Spearheaded technical discovery and platform execution for documentation and mobile check-in journeys across global markets.',
      imageSrc: IMAGES.projects.sixt,
      imageAlt: 'Sixt mobile check-in and micro-frontend platform',
      initials: 'SX',
      role: 'Software Development Engineer III',
      company: 'Sixt',
      duration: 'Sep 2021 - Oct 2023',
      location: 'Munich & Bengaluru',
      summary: 'Spearheaded technical discovery and platform execution for documentation and mobile check-in journeys across global markets.',
      achievements: [
        'Built web mobile check-in platform from scratch, reducing counter pickups by 15% globally.',
        'Introduced micro-frontend architecture for post-purchase flows, improving modularity and scalability.',
        'Improved conversion metrics by 20% through performance, latency optimization, and A/B testing.',
      ],
      technologies: [
        'React',
        'TypeScript',
        'Micro-frontends',
        'A/B Testing',
        'Performance',
      ],
    },
    {
      id: 'lowes-lead-software-engineer',
      title: "Lowe's search and product listing platform",
      description: "Led front-end engineering for lowes.com search and product listing, focusing on SSR architecture and platform performance.",
      imageSrc: IMAGES.projects.lowes,
      imageAlt: "Lowe's search and product listing platform",
      initials: 'LW',
      role: 'Lead Software Engineer',
      company: "Lowe's",
      duration: 'May 2020 - Sep 2021',
      location: 'Bengaluru, India',
      summary: "Led front-end engineering for lowes.com search and product listing, focusing on SSR architecture and platform performance.",
      achievements: [
        'Implemented isomorphic web architecture with Node.js BFF and server-side rendering.',
        'Boosted web vitals and observability for customer-facing flows.',
        'Improved platform efficiency and reduced cloud costs on GCP.',
      ],
      technologies: [
        'React',
        'Node.js',
        'SSR',
        'BFF',
        'GCP',
        'Observability',
      ],
    },
  ],
};
